version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: arbre
    volumes:
      - dbarbre:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=pass
    depends_on:
      - db
volumes:
  dbarbre: